import json

from fbs_runtime.licensing import pack_license_key

secret_json = (
    "src/build/settings/secret.json"  # This file was generated by `init_licensing`
)
privkey = json.load(open(secret_json))["licensing_privkey"]
print(pack_license_key({"email": "user@domain.com"}, privkey))
