[project]
name = "ytmusic-deleter-cli"
version = "2.0.0"
requires-python = "<3.13,>=3.8.1"
dependencies = [
    "click",
    "enlighten",
]

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.pdm]
distribution = true

[project.scripts]
ytmusic-deleter = "packages.cli.cli:cli"
