# This workflow builds and tests the Linux installer for YTMusic Deleter.

name: Build and Verify (Linux)

on:
  push:
    branches: # prevent push on tags since that's handled by another workflow
      - '**'
    paths-ignore:
      - '**.md'
      - '.flake8'
      - '.gitignore'
      - '.pre-commit-comfig.yaml'
      - '**/build-exe.yml'
      - '**/build-dmg.yml'
      - '**/pytest.yml'
      - '**/release.yml'
  pull_request:
  workflow_dispatch:
  workflow_call:
  schedule:
    - cron: '0 10 * * *'

concurrency:
  group: build-deb-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-22.04
    outputs:
      installer-version: ${{ steps.create_installer.outputs.version }}
    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0
    - uses: pdm-project/setup-pdm@v4
    - name: Install dependencies
      run: |
        sudo apt update && sudo apt install -y libegl1 libegl1-mesa
        pdm install --no-editable
    - name: Run CLI from venv
      id: run-cli
      run: |
        . .venv/bin/activate
        echo "version=$(ytmusic-deleter --version)"
    - name: Run GUI app
      run: |

        # Makes app run headless
        export QT_QPA_PLATFORM=offscreen

        # Launch the GUI app and kill it after 10 seconds, saving the output.
        set +e
        timeout 10s pdm gui
        status=$?
        set -e
        if [ "$status" = 124 ]; then
          echo "GUI started and was still running after 10s"
        else
          echo "GUI failed with exit code $status"
          exit 1
        fi
    - name: Freeze exe
      run: |
        pdm run pyinstaller gui/src/main/python/gui.spec
    - name: Run frozen exe
      run: |

        # Makes app run headless
        export QT_QPA_PLATFORM=offscreen

        # Launch frozen app and kill it after 10 seconds
        set +e
        timeout 10s ./dist/YTMusic_Deleter/YTMusic_Deleter
        status=$?
        set -e
        if [ "$status" = 124 ]; then
          echo "GUI started and was still running after 10s"
        else
          echo "GUI failed with exit code $status"
          exit 1
        fi
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ruby
    - name: Install fpm
      run: |
        sudo gem install fpm
    - name: Create installer
      id: create_installer
      run: |
        mkdir -p gui/target
        VERSION=$(python -c "from ytmusic_deleter._version import __version__; print(__version__)" )
        fpm -s dir -t deb -n ytmusic-deleter -v "$VERSION" \
            --deb-compression xz \
            --description "Easily delete your YouTube Music library" \
            --maintainer "apastel <alex.r.pastel@gmail.com>" \
            ./dist/YTMusic_Deleter/=/opt/YTMusic_Deleter/
        echo "version=$VERSION" >> $GITHUB_OUTPUT
    - name: Save .deb as artifact
      uses: actions/upload-artifact@v7
      with:
        path: ./ytmusic-deleter_${{ steps.create_installer.outputs.version }}_amd64.deb
        archive: false

  verify:
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v8
        with:
          name: ytmusic-deleter_${{ needs.build.outputs.installer-version }}_amd64.deb
      - name: Run installer
        run: |
          sudo dpkg -i ./ytmusic-deleter_${{ needs.build.outputs.installer-version }}_amd64.deb
      - name: Install dependencies
        run: |
          sudo apt update && sudo apt install -y libegl1
      - name: Run application
        run: |

          # Makes app run headless
          export QT_QPA_PLATFORM=offscreen

          # Launch the installed app and kill it after 10s
          set +e
          timeout 10s /opt/YTMusic_Deleter/YTMusic_Deleter
          status=$?
          set -e
          if [ "$status" = 124 ]; then
            echo "GUI started and was still running after 10s"
          else
            echo "GUI failed with exit code $status"
            exit 1
          fi
