# This workflow builds and tests the Linux installer for YTMusic Deleter.

name: Build and Verify (Linux)

on:
  push:
    branches: # prevent push on tags since that's handled by another workflow
      - '**'
    paths-ignore:
      - '**.md'
      - '.flake8'
      - '.gitignore'
      - '.pre-commit-comfig.yaml'
      - '**/build-exe.yml'
      - '**/build-dmg.yml'
      - '**/pytest.yml'
      - '**/release.yml'
  pull_request_target:
    branches: [ main ]
  workflow_dispatch:
  workflow_call:
  schedule:
    - cron: '0 10 * * *'

concurrency:
  group: build-deb-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-22.04
    outputs:
      installer-version: ${{ steps.run-cli.outputs.version }}
      cli-version: ${{ steps.run-cli.outputs.version }}
    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0
    - uses: pdm-project/setup-pdm@v4
    - name: Install dependencies
      run: |
        sudo apt update && sudo apt install -y libegl1 libegl1-mesa
        pdm install --no-editable
    - name: Run CLI from venv
      id: run-cli
      run: |
        . .venv/bin/activate
        echo "version=$(ytmusic-deleter --version)" >> $GITHUB_OUTPUT
    - name: Run GUI app
      run: |

        # Store the version argument
        version_str="${{ steps.run-cli.outputs.version }}"

        # Makes app run headless
        export QT_QPA_PLATFORM=offscreen

        # Launch the GUI app and kill it after 10 seconds, saving the output.
        output=$(timeout 10s pdm gui || true)

        # Check if the output contains the right CLI version
        if grep -q "$version_str" <<< "$output"; then
            echo "GUI is running the right CLI version: $version_str"
        else
            echo "$version_str not found in output, which was the following:"
            echo $output
            exit 1
        fi
    - name: Freeze prep
      run: |
        pdm freeze-prep
    - name: Freeze exe
      run: |
        pdm run pyinstaller gui/src/main/python/gui.spec
    - name: Run frozen exe
      run: |

        # Store the version argument
        version_str="${{ steps.run-cli.outputs.version }}"

        # Makes app run headless
        export QT_QPA_PLATFORM=offscreen

        # Launch the frozen app and kill it after 10 seconds, saving the output.
        output=$(timeout 10s ./gui/target/YTMusic_Deleter/YTMusic_Deleter || true)

        # Check if the output contains the right CLI version
        if grep -q "$version_str" <<< "$output"; then
            echo "GUI is running the right CLI version: $version_str"
        else
            echo "$version_str not found in output, which was the following:"
            echo $output
            exit 1
        fi
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ruby
    - name: Install fpm
      run: |
        sudo gem install fpm
    - name: Create installer
      run: |
        VERSION=$(python -c "from ytmusic_deleter._version import __version__; print(__version__)")
        fpm -s dir -t deb -n YTMusic_Deleter -v "$VERSION" \
            --deb-compression xz \
            --description "Easily delete your YouTube Music library" \
            --maintainer "apastel <alex.r.pastel@gmail.com>" \
            ./gui/target/YTMusic_Deleter/=/opt/YTMusic_Deleter/
    - name: Save .deb as artifact
      id: upload_deb
      uses: actions/upload-artifact@v7
      with:
        name: installer-deb
        path: ./YTMusic_Deleter_*.deb

  verify:
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v8
        with:
          name: installer-deb
      - name: Run installer
        run: |
          sudo dpkg -i ./YTMusic_Deleter_*.deb
      - name: Install dependencies
        run: |
          sudo apt update && sudo apt install -y libegl1
      - name: Run application
        run: |

          # Makes app run headless
          export QT_QPA_PLATFORM=offscreen
          logfile="$HOME/YTMusic_Deleter/logs/ytmusic-deleter-gui*.log"
          timeout 10s /opt/YTMusic_Deleter/YTMusic_Deleter || true
          version_str="${{ needs.build.outputs.cli-version }}"
          if grep -q "$version_str" $logfile; then
            echo "GUI is running the right CLI version: $version_str"
          else
            echo "The string "$version_str" was not found in $logfile, contents below:"
            cat $logfile
            exit 1
          fi
