# This workflow builds and tests the macOS installer for YTMusic Deleter.

name: Build and Verify (macOS)

on:
  push:
    branches: # prevent push on tags since that's handled by another workflow
      - '**'
    paths-ignore:
      - '**.md'
      - '.flake8'
      - '.gitignore'
      - '.pre-commit-comfig.yaml'
      - '**/build-exe.yml'
      - '**/build-deb.yml'
      - '**/pytest.yml'
      - '**/release.yml'
  pull_request:
  workflow_dispatch:
  workflow_call:
  schedule:
    - cron: '0 10 * * *'

concurrency:
  group: build-dmg-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  build:
    strategy:
      matrix:
        os: [macos-14, macos-15, macos-26]
    runs-on: ${{ matrix.os }}
    outputs:
      installer-version: ${{ steps.create_installer.outputs.version }}
    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0
    - uses: pdm-project/setup-pdm@v4
    - name: Install dependencies
      run: |

        pdm install --no-editable

        # adds `timeout` command
        brew install coreutils
    - name: Run CLI from venv
      id: run-cli
      run: |
        . .venv/bin/activate
        echo "version=$(ytmusic-deleter --version)"
    - name: Run GUI app
      run: |

        # Makes app run headless
        export QT_QPA_PLATFORM=offscreen

        # Launch the GUI app and kill it after 10 seconds, saving the output.
        set +e
        timeout 10s pdm gui
        status=$?
        set -e
        if [ "$status" = 124 ]; then
          echo "GUI started and was still running after 10s"
        else
          echo "GUI failed with exit code $status"
          exit 1
        fi
    - name: Freeze exe
      run: |
        pdm run pyinstaller gui/src/main/python/gui.spec
    - name: List dist
      shell: pwsh
      run: |
        Get-ChildItem -Path ".\dist" -Recurse
    - name: List build
      shell: pwsh
      run: |
        Get-ChildItem -Path ".\build" -Recurse
    - name: List gui
      shell: pwsh
      run: |
        Get-ChildItem -Path ".\gui" -Recurse
    - name: Run frozen exe
      run: |

        # Makes app run headless
        export QT_QPA_PLATFORM=offscreen

        # Launch the frozen app and kill it after 10 seconds
        set +e
        timeout 10s ./dist/YTMusic_Deleter.app/Contents/MacOS/YTMusic_Deleter
        status=$?
        set -e
        if [ "$status" = 124 ]; then
          echo "GUI started and was still running after 10s"
        else
          echo "GUI failed with exit code $status"
          exit 1
        fi
    - name: Create installer
      id: create_installer
      uses: nick-fields/retry@v3
      with:
        command: |
          brew install create-dmg
          VERSION=$(python -c "from ytmusic_deleter._version import __version__; print(__version__)")
          create-dmg \
            --volname "YTMusic Deleter" \
            --volicon "./dist/YTMusic_Deleter.app/Contents/Resources/YTMusic_Deleter.icns" \
            --window-pos 200 120 \
            --window-size 800 400 \
            --icon-size 100 \
            --icon "YTMusic_Deleter.app" 200 190 \
            --hide-extension "YTMusic_Deleter.app" \
            --app-drop-link 600 185 \
            "mac-installer-to-be-renamed.dmg" \
            "./dist/YTMusic_Deleter.app"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
        max_attempts: 10
        timeout_minutes: 20
    - name: Rename installer per version
      id: rename-installer
      run: |

        if [[ "${{ matrix.os }}" == "macos-14" ]]; then
          MAC_VERSION=14
        elif [[ "${{ matrix.os }}" == "macos-15" ]]; then
          MAC_VERSION=15
        elif [[ "${{ matrix.os }}" == "macos-26" ]]; then
          MAC_VERSION=26
        fi
        mv ./mac-installer-to-be-renamed.dmg \
           ./YTMusic_Deleter-${{ steps.create_installer.outputs.version }}-MacOS-$MAC_VERSION-Installer_arm.dmg
        echo "MAC_VERSION=$MAC_VERSION" >> $GITHUB_ENV
    - name: Save .dmg as artifact
      id: upload_dmg
      uses: actions/upload-artifact@v7
      with:
        name: installer-dmg-${{ matrix.os }}
        path: ./YTMusic_Deleter-${{ steps.create_installer.outputs.version }}-MacOS-${{ env.MAC_VERSION }}-Installer_arm.dmg
      env:
        MAC_VERSION: ${{ env.MAC_VERSION }}

  verify:
    strategy:
      matrix:
        os: [macos-14, macos-15, macos-26]
    runs-on: ${{ matrix.os }}
    needs: build
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v8
        with:
          name: installer-dmg-${{ matrix.os }}
      - name: Attach app image
        run: |

          # Have to redefine MAC_VERSION
          if [[ "${{ matrix.os }}" == "macos-14" ]]; then
            MAC_VERSION=14
          elif [[ "${{ matrix.os }}" == "macos-15" ]]; then
            MAC_VERSION=15
          elif [[ "${{ matrix.os }}" == "macos-26" ]]; then
            MAC_VERSION=26
          fi
          hdiutil attach ./YTMusic_Deleter-${{ needs.build.outputs.installer-version }}-MacOS-$MAC_VERSION-Installer_arm.dmg
      - name: Install dependencies
        run: |

          # adds `timeout` command
          brew install coreutils
      - name: Run application
        run: |

          # Makes app run headless
          export QT_QPA_PLATFORM=offscreen

          # Launch the installed app and kill it after 10s
          set +e
          timeout 10s /Volumes/YTMusic_Deleter/YTMusic_Deleter.app/Contents/MacOS/YTMusic_Deleter
          status=$?
          set -e
          if [ "$status" = 124 ]; then
            echo "GUI started and was still running after 10s"
          else
            echo "GUI failed with exit code $status"
            exit 1
          fi
