name: Code coverage

on:
  push:
    branches:
      - main
    paths:
      - cli/**
  pull_request:
    branches:
      - main
    paths:
      - cli/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.x
    - name: Setup PDM
      uses: pdm-project/setup-pdm@v4
    - name: create-json
      uses: jsdaniell/create-json@v1.2.3
      with:
        name: "oauth.json"
        dir: "cli/tests/resources"
        json: ${{ secrets.OAUTH_JSON }}
    - name: Install dependencies
      run: pdm install
    - name: Generate coverage report
      env:
        HEADERS_AUTH: ${{ secrets.BROWSER_JSON }}
        TEST_CFG: ${{ secrets.TEST_CFG }}
      run: |
        curl -o cli/tests/resources/test.mp3 https://www.kozco.com/tech/piano2-CoolEdit.mp3
        cat <<< "$HEADERS_AUTH" > cli/tests/resources/browser.json
        cat <<< "$TEST_CFG" > cli/tests/resources/test.cfg
        (echo "===== tests attempt: 1 ====" && pdm run pytest) || \
        (echo "===== tests attempt: 2 ====" && pdm run pytest)
        pdm run coverage xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: apastel/ytmusic-deleter
    