name: Update dependencies

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * 6"

concurrency:
  group: pdm-update
  cancel-in-progress: true

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v6

      - name: Update dependencies
        uses: pdm-project/update-deps-action@main
