name: Pytest

on:
  push:
    paths:
      - ytmusic_deleter/**
      - tests/**
      - '**/pytest.yml'
      - pyproject.toml
      - pdm.lock
  pull_request:
    paths:
      - ytmusic_deleter/**
      - tests/**
      - '**/pytest.yml'
      - pyproject.toml
      - pdm.lock
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * *'

concurrency:
  group: pytest

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.x
    - name: Setup PDM
      uses: pdm-project/setup-pdm@v4
    - name: Install dependencies
      run: pdm install -dG test
    - name: Create test resources
      env:
        HEADERS_AUTH: ${{ secrets.BROWSER_JSON }}
        OAUTH_JSON: ${{ secrets.OAUTH_JSON }}
        TEST_CFG: ${{ secrets.TEST_CFG }}
      run: |
        wget -O 'tests/resources/Jennifer Lost the War.mp3' https://drive.google.com/uc?id=18AP7mQqQxqj2_delNyhoCNa6UCUCN9-P
        cat <<< "$HEADERS_AUTH" > tests/resources/browser.json
        cat <<< "$OAUTH_JSON" > tests/resources/oauth.json
        cat <<< "$TEST_CFG" > tests/resources/test.cfg
    - name: Run pytest
      uses: nick-fields/retry@v3
      with:
        command: pdm run pytest
        max_attempts: 2
        timeout_minutes: 20
    - name: Generate coverage report
      run: |
        pdm run coverage xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: apastel/ytmusic-deleter
