name: Create Tag

on:
  workflow_dispatch:
    inputs:
      revision:
        description: 'The tag name'
        required: true

concurrency:
  group: tag
  cancel-in-progress: false

jobs:
  create-tag:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      actions: write
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Create and push tag
        run: |
          TAG="${{ inputs.revision }}"
          git tag "$TAG"
          git push origin "$TAG"
      - name: Dispatch release workflow
        uses: actions/github-script@v8
        with:
          github-token: ${{ github.token }}
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: 'apastel',
              repo: 'ytmusic-deleter',
              workflow_id: 'release.yml',
              ref: '${{ inputs.revision }}'
            })
